
services:
  mongo:
    image: mongo:6
    container_name: eventflow-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: eventflow-redis
    ports:
      - "6379:6379"

  users-service:
    build: .
    container_name: eventflow-users
    depends_on:
      - mongo
      - redis
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongo:27017/eventflow_users_service
      - REDIS_URL=redis://redis:6379
      - ANON_SALT=change-me
    ports:
      - "3001:3001"
    restart: unless-stopped

  events-service:
    build: .
    container_name: eventflow-events
    depends_on:
      - mongo
    environment:
      - PORT=3002
      - EVENTS_MONGODB_URI=mongodb://mongo:27017/eventflow_events_service
    command: ["npm", "run", "start:events"]
    ports:
      - "3002:3002"
    restart: unless-stopped

  reservations-service:
    build: .
    container_name: eventflow-reservations
    depends_on:
      - mongo
      - users-service
      - events-service
    environment:
      - PORT=3003
      - RESERVATIONS_MONGODB_URI=mongodb://mongo:27017/eventflow_reservations_service
      - USERS_BASE_URL=http://users-service:3001
      - EVENTS_BASE_URL=http://events-service:3002
      - PAYMENT_SUCCESS_RATE=0.7
    command: ["npm", "run", "start:reservations"]
    ports:
      - "3003:3003"
    restart: unless-stopped

volumes:
  mongo_data:
