version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: eventflow-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: eventflow-redis
    ports:
      - "6379:6379"

  users-service:
    build: .
    container_name: eventflow-users
    depends_on:
      - mongo
      - redis
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongo:27017/eventflow_users_service
      - REDIS_URL=redis://redis:6379
    ports:
      - "3001:3001"
    restart: unless-stopped

volumes:
  mongo_data:
